In [4]:
import numpy as np

salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

media_salarial = np.mean(salarios)

print(media_salarial)

3714.285714285714


In [5]:
funcionarios_acima_media = np.where(salarios > media_salarial)
print(funcionarios_acima_media)

(array([2, 4, 5, 6], dtype=int64),)


In [6]:
print(salarios[funcionarios_acima_media])

[4000 4500 4000 5000]


In [7]:
print(salarios[salarios > media_salarial])

[4000 4500 4000 5000]


In [8]:
print(np.where(salarios > media_salarial,  "acima da média", "abaixo da média"))

['abaixo da média' 'abaixo da média' 'acima da média' 'abaixo da média'
 'acima da média' 'acima da média' 'acima da média']


In [9]:
salarios_bonus = np.where(salarios < media_salarial, salarios * 1.1, salarios)

print(salarios)
print(salarios_bonus)

[3000 3500 4000 2000 4500 4000 5000]
[3300. 3850. 4000. 2200. 4500. 4000. 5000.]


In [10]:
print(np.where((salarios>= 3000) & (salarios <= 4500)))

(array([0, 1, 2, 4, 5], dtype=int64),)


In [13]:
salarios_ajustados = np.where((salarios >= 3000) & (salarios <= 4500), salarios * 1.05, salarios)
print(salarios_ajustados)

[3150. 3675. 4200. 2000. 4725. 4200. 5000.]


In [14]:
np.where((salarios_ajustados < 3000) | (salarios_ajustados > 4500))

(array([3, 4, 6], dtype=int64),)

In [15]:
salario_segundo_ajuste = np.where((salarios_ajustados < 3000) | (salarios_ajustados > 4500), salarios_ajustados * 1.10, salarios_ajustados)
print(salario_segundo_ajuste)

[3150.  3675.  4200.  2200.  5197.5 4200.  5500. ]
